CREATE TABLE `negative_monitor_tasks` (
	`task_id` text PRIMARY KEY NOT NULL,
	`note_id` text NOT NULL,
	`generated_at` text NOT NULL,
	`mode` text DEFAULT 'scheduled' NOT NULL,
	`nickname` text DEFAULT '' NOT NULL,
	`link` text DEFAULT '' NOT NULL,
	`category` text DEFAULT '' NOT NULL,
	`publish_date` text DEFAULT '' NOT NULL,
	`current_deadline` text DEFAULT '' NOT NULL,
	`judgment_node` text DEFAULT '' NOT NULL,
	`delivery_status` text DEFAULT '' NOT NULL,
	`spend_3d` real DEFAULT 0 NOT NULL,
	`comments_total` integer DEFAULT 0 NOT NULL,
	`comments_3d` integer,
	`comments_7d` integer,
	`extension_reason` text DEFAULT '' NOT NULL,
	`new_deadline` text DEFAULT '' NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`owner` text DEFAULT '' NOT NULL,
	`notes` text DEFAULT '' NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	`completed_at` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
