CREATE TABLE IF NOT EXISTS `risk_alert_tasks` (
  `note_id` text PRIMARY KEY NOT NULL,
  `data_date` text NOT NULL,
  `title` text NOT NULL,
  `link` text DEFAULT '' NOT NULL,
  `creator` text DEFAULT '' NOT NULL,
  `publish_date` text DEFAULT '' NOT NULL,
  `category` text DEFAULT '' NOT NULL,
  `direction` text DEFAULT '' NOT NULL,
  `delivery_status` text NOT NULL,
  `first_spend_date` text DEFAULT '' NOT NULL,
  `last_spend_date` text DEFAULT '' NOT NULL,
  `delivery_days` integer DEFAULT 0 NOT NULL,
  `no_spend_days` integer DEFAULT 0 NOT NULL,
  `spend` real DEFAULT 0 NOT NULL,
  `action_clicks` integer DEFAULT 0 NOT NULL,
  `action_cost` real DEFAULT 0 NOT NULL,
  `category_median_cost` real DEFAULT 0 NOT NULL,
  `risk_ratio` real,
  `risk_reason` text DEFAULT '' NOT NULL,
  `account` text DEFAULT '' NOT NULL,
  `spend_3d` real DEFAULT 0 NOT NULL,
  `action_clicks_3d` integer DEFAULT 0 NOT NULL,
  `action_cost_3d` real DEFAULT 0 NOT NULL,
  `spend_7d` real DEFAULT 0 NOT NULL,
  `action_clicks_7d` integer DEFAULT 0 NOT NULL,
  `action_cost_7d` real DEFAULT 0 NOT NULL,
  `spend_prev_7d` real DEFAULT 0 NOT NULL,
  `action_clicks_prev_7d` integer DEFAULT 0 NOT NULL,
  `action_cost_prev_7d` real DEFAULT 0 NOT NULL,
  `cost_change_7d` real,
  `threshold_cost` real DEFAULT 0 NOT NULL,
  `benchmark_samples` integer DEFAULT 0 NOT NULL,
  `benchmark_scope` text DEFAULT '' NOT NULL,
  `benchmark_multiplier` real DEFAULT 1.5 NOT NULL,
  `risk_trend` text DEFAULT '' NOT NULL,
  `risk_priority` text DEFAULT 'P1' NOT NULL,
  `owner` text DEFAULT '' NOT NULL,
  `resolution` text DEFAULT 'pending' NOT NULL,
  `action_type` text DEFAULT '' NOT NULL,
  `notes` text DEFAULT '' NOT NULL,
  `version` integer DEFAULT 1 NOT NULL,
  `resolved_at` text,
  `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS `risk_alert_activity` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  `note_id` text NOT NULL,
  `actor` text NOT NULL,
  `action` text NOT NULL,
  `detail` text DEFAULT '{}' NOT NULL,
  `created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS `risk_alert_status_idx` ON `risk_alert_tasks` (`delivery_status`, `resolution`, `spend`);
CREATE INDEX IF NOT EXISTS `risk_alert_activity_idx` ON `risk_alert_activity` (`note_id`, `id`);
