import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const dashboardMeta = sqliteTable("dashboard_meta", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const maintenanceTasks = sqliteTable("maintenance_tasks", {
  taskId: text("task_id").primaryKey(),
  noteId: text("note_id").notNull(),
  taskDate: text("task_date").notNull(),
  cycleNumber: integer("cycle_number").notNull().default(1),
  title: text("title").notNull(),
  nickname: text("nickname").notNull().default(""),
  link: text("link").notNull(),
  publishDate: text("publish_date").notNull(),
  priority: text("priority").notNull(),
  score: integer("score").notNull().default(0),
  cadenceDays: integer("cadence_days").notNull().default(1),
  reasons: text("reasons").notNull().default("[]"),
  spend3d: real("spend_3d").notNull().default(0),
  spend7d: real("spend_7d").notNull().default(0),
  spendTotal: real("spend_total").notNull().default(0),
  activeDays7d: integer("active_days_7d").notNull().default(0),
  actionClicks3d: integer("action_clicks_3d").notNull().default(0),
  commentsTotal: integer("comments_total").notNull().default(0),
  comments3d: integer("comments_3d"),
  comments7d: integer("comments_7d"),
  status: text("status").notNull().default("pending"),
  owner: text("owner").notNull().default(""),
  reviewDone: integer("review_done", { mode: "boolean" }).notNull().default(false),
  placementDone: integer("placement_done", { mode: "boolean" }).notNull().default(false),
  dealerGuardDone: integer("dealer_guard_done", { mode: "boolean" }).notNull().default(false),
  replyDone: integer("reply_done", { mode: "boolean" }).notNull().default(false),
  recheckDone: integer("recheck_done", { mode: "boolean" }).notNull().default(false),
  reviewStatus: text("review_status").notNull().default("pending"),
  placementStatus: text("placement_status").notNull().default("pending"),
  dealerGuardStatus: text("dealer_guard_status").notNull().default("pending"),
  replyStatus: text("reply_status").notNull().default("pending"),
  recheckStatus: text("recheck_status").notNull().default("pending"),
  resolutionStatus: text("resolution_status").notNull().default("pending"),
  placementCount: integer("placement_count").notNull().default(0),
  riskTag: text("risk_tag").notNull().default(""),
  notes: text("notes").notNull().default(""),
  notesHtml: text("notes_html").notNull().default(""),
  version: integer("version").notNull().default(1),
  completedAt: text("completed_at"),
  completedComments: integer("completed_comments"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const negativeMonitorTasks = sqliteTable("negative_monitor_tasks", {
  taskId: text("task_id").primaryKey(),
  noteId: text("note_id").notNull(),
  generatedAt: text("generated_at").notNull(),
  mode: text("mode").notNull().default("scheduled"),
  nickname: text("nickname").notNull().default(""),
  link: text("link").notNull().default(""),
  category: text("category").notNull().default(""),
  publishDate: text("publish_date").notNull().default(""),
  currentDeadline: text("current_deadline").notNull().default(""),
  judgmentNode: text("judgment_node").notNull().default(""),
  deliveryStatus: text("delivery_status").notNull().default(""),
  spend3d: real("spend_3d").notNull().default(0),
  commentsTotal: integer("comments_total").notNull().default(0),
  comments3d: integer("comments_3d"),
  comments7d: integer("comments_7d"),
  extensionReason: text("extension_reason").notNull().default(""),
  newDeadline: text("new_deadline").notNull().default(""),
  status: text("status").notNull().default("pending"),
  owner: text("owner").notNull().default(""),
  notes: text("notes").notNull().default(""),
  version: integer("version").notNull().default(1),
  completedAt: text("completed_at"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const activityLog = sqliteTable("activity_log", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  taskId: text("task_id").notNull(),
  actor: text("actor").notNull(),
  action: text("action").notNull(),
  detail: text("detail").notNull().default("{}"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const operationEvents = sqliteTable("operation_events", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  taskId: text("task_id").notNull(),
  noteId: text("note_id").notNull(),
  cycleNumber: integer("cycle_number").notNull(),
  operationType: text("operation_type").notNull(),
  actor: text("actor").notNull(),
  detail: text("detail").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const noteUploads = sqliteTable("note_uploads", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  taskId: text("task_id").notNull(),
  noteId: text("note_id").notNull(),
  actor: text("actor").notNull(),
  objectKey: text("object_key").notNull(),
  fileName: text("file_name").notNull(),
  contentType: text("content_type").notNull(),
  size: integer("size").notNull(),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
